#!/usr/bin/env bash
set -euo pipefail

workflow=".github/workflows/publish-ghcr.yml"
validation_workflow=".github/workflows/validate.yml"
resolver=".github/scripts/resolve-publication-binding.sh"
binding_tests=".github/scripts/test-publication-binding.sh"
cleanup_tests=".github/scripts/test-resolver-cleanup.sh"
dockerfile="Dockerfile"
readme="README.md"

test -f "${workflow}"
test -f "${validation_workflow}"
test -f "${resolver}"
test -f "${binding_tests}"
test -x "${cleanup_tests}"
test -f "${dockerfile}"
test -f "${readme}"

grep -Fqx '  push:' "${workflow}"
grep -Fqx '    branches: [master]' "${workflow}"
! grep -Fq 'pull_request_target:' "${workflow}"
! grep -Fq 'workflow_dispatch:' "${workflow}"

grep -Fq 'test "${#parents[@]}" -eq 2' "${workflow}"
grep -Fq 'test "${parents[0]}" = "${PREVIOUS_MASTER_SHA}"' "${workflow}"
grep -Fq 'export MERGE_HEAD_SHA="${parents[1]}"' "${workflow}"
grep -Fq 'bash .github/scripts/resolve-publication-binding.sh' "${workflow}"
grep -Fq 'ref: ${{ steps.trust.outputs.pr_head_sha }}' "${workflow}"

grep -Fq -- '--head' "${workflow}"
! grep -Fq -- '--request HEAD' "${workflow}"
grep -Fq 'Refusing to overwrite existing GHCR tag' "${workflow}"
grep -Fq -- '--request PATCH' "${workflow}"
grep -Fq -- '--data '"'"'{"visibility":"private"}'"'"'' "${workflow}"
grep -Fq '.visibility == "private"' "${workflow}"
grep -Fq 'tag_digest="$(read_manifest_digest "${TAG_SUFFIX}"' "${workflow}"
grep -Fq 'digest_reference_digest="$(read_manifest_digest "${DIGEST}"' "${workflow}"

grep -Fq 'Create durable publication binding' "${validation_workflow}"
grep -Fq 'Upload durable publication binding' "${validation_workflow}"
grep -Fq 'test "${GITHUB_RUN_ATTEMPT}" = 1' "${validation_workflow}"
grep -Fq 'write_binding_document publication-binding.json' "${validation_workflow}"
grep -Fq 'verify_binding_document publication-binding.json' "${validation_workflow}"
grep -Fq 'publication-binding-${{ github.event.pull_request.head.sha }}-${{ github.run_id }}-${{ github.run_attempt }}' "${validation_workflow}"

grep -Fq 'select(.head.repo.full_name == $repository)' "${resolver}"
grep -Fq 'select(.head.repo.id == $repository_id)' "${resolver}"
grep -Fq 'select(.head_branch == $head_ref)' "${resolver}"
grep -Fq 'select(.head_repository.full_name == $head_repository)' "${resolver}"
grep -Fq 'select(.run_attempt == 1)' "${resolver}"
grep -Fq -- "--arg schema 'neolink-publication-binding/v1'" "${resolver}"
grep -Fq 'reject_next_page "${runs_headers}"' "${resolver}"
grep -Fq 'verify_validation_jobs' "${resolver}"
grep -Fq 'verify_binding_document' "${resolver}"
grep -Fq 'Close the rerun race' "${resolver}"
! grep -Fq '.pull_requests' "${resolver}"

bash -n "${resolver}"
bash -n "${binding_tests}"
bash -n "${cleanup_tests}"
bash "${binding_tests}"
bash "${cleanup_tests}"

grep -Fq 'COPY LICENSE /usr/share/licenses/neolink/LICENSE' "${dockerfile}"
grep -Fq '> /usr/share/doc/neolink/SOURCE_OFFER' "${dockerfile}"
grep -Fq 'SOURCE_SHA=${{ steps.trust.outputs.pr_head_sha }}' "${workflow}"
grep -Fq 'test -s /usr/share/licenses/neolink/LICENSE' "${workflow}"
grep -Fq 'test -s /usr/share/doc/neolink/SOURCE_OFFER' "${workflow}"
grep -Fq '/usr/share/licenses/neolink/LICENSE' "${readme}"
grep -Fq '/usr/share/doc/neolink/SOURCE_OFFER' "${readme}"
